apiVersion: v1
kind: Secret
metadata:
  name: ekart-secrets
type: Opaque
stringData:
  dbUsername: "postgres"
  dbPassword: "postgres"
  jsonSecretKey: "ekartSecretKey"
  adminPassword: "adminPasswordValue"
  stripeApiKey: "fake-stripe-api-key"
  endpointSecret: "fake-stripe-endpoint-secret"
  emailUsername: "your-email@example.com"
  emailPassword: "your-email-password"
